export const RPC_ENDPOINT = "https://testnet-rpc.qubicdev.com";

export const API_ENDPOINT = "https://testnet-rpc.qubicdev.com";

export const DEFAULT_TX_SIZE = 144;

export const DEFAULT_TICK_OFFSET = 10;

export const NOSTROMO_TIER_FACEHUGGER_STAKE_AMOUNT = 20000000;
export const NOSTROMO_TIER_CHESTBURST_STAKE_AMOUNT = 100000000;
export const NOSTROMO_TIER_DOG_STAKE_AMOUNT = 200000000;
export const NOSTROMO_TIER_XENOMORPH_STAKE_AMOUNT = 800000000;
export const NOSTROMO_TIER_WARRIOR_STAKE_AMOUNT = 3200000000;
export const NOSTROMO_QX_TOKEN_ISSUANCE_FEE = 1000000000;

export const NOSTROMO_TIER_FACEHUGGER_POOL_WEIGHT = 55;
export const NOSTROMO_TIER_CHESTBURST_POOL_WEIGHT = 300;
export const NOSTROMO_TIER_DOG_POOL_WEIGHT = 750;
export const NOSTROMO_TIER_XENOMORPH_POOL_WEIGHT = 3050;
export const NOSTROMO_TIER_WARRIOR_POOL_WEIGHT = 13750;

export const NOSTROMO_TIER_FACEHUGGER_UNSTAKE_FEE = 5;
export const NOSTROMO_TIER_CHESTBURST_UNSTAKE_FEE = 4;
export const NOSTROMO_TIER_DOG_UNSTAKE_FEE = 3;
export const NOSTROMO_TIER_XENOMORPH_UNSTAKE_FEE = 2;
export const NOSTROMO_TIER_WARRIOR_UNSTAKE_FEE = 1;
export const NOSTROMO_CREATE_PROJECT_FEE = 100000000;
